services:
  hiring-web:
    restart: always
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bash -c "python manage.py collectstatic --noinput --clear && python manage.py migrate --noinput && gunicorn -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 core.asgi:application --workers 4 --timeout 120 --worker-connections 1000"
    expose:
      - 8000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - hiring-db
      - hiring-redis
    ports:
      - "8000:8000"

  hiring-db:
    image: kartoza/postgis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - "5432:5432"
    expose:
      - 5432

  hiring-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - 6379

volumes:
  postgres_data:
